In [2]:
import pandas as pd
print("OK")

OK

In [7]:
import sys
sys.path.append("..")

from src.features import extract_symptoms
import pandas as pd

# load data
df_raw = pd.read_excel("../data/raw/covid.xlsx")

# run function
df_symptoms = extract_symptoms(df_raw)

# check output
df_symptoms.head()

,Fever,Myalgia,Chills,Fatigue,Sweating,Anorexia,Sore_Throat,Sneezing,Cough,Dyspnea,...,Ageusia,Chest_Pain,Palpitations,Nausea,Vomiting,Abdominal_Pain,Diarrhea,Depression,Sleep_Disorder,Headache
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
4,0,0,1,0,0,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
import sys
sys.path.append("..")

#import importlib
import src.features as features

#importlib.reload(features)

df_pmh = features.extract_pmh(df_raw)

print(df_pmh.shape)
df_pmh.head()

(16780, 28)

,Cancer,Organ_Transplant,Chronic_Kidney_Disease,Dialysis,Cancer_Type,Solid_Organ_Transplant,Asthma,Chronic_Respiratory_Disease,Hypertension,Myocardial_Infarction,...,Seizure,Diabetes_Type1,Diabetes_Type2,Hypothyroidism,Hyperthyroidism,Insulin_Use,Rheumatoid_Arthritis,Lupus,Behcet,Sjogren
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
import importlib
import src.features as features

importlib.reload(features)

df_vax = features.extract_vaccination(df_raw)

print(df_vax.shape)
df_vax.head()

(16780, 2)

   Vaccinated  Vaccine_Doses
0           0            0.0
1           0            0.0
2           0            0.0
3           0            0.0
4           1            2.0

In [11]:
print("Vaccinated %:", round(df_vax['Vaccinated'].mean() * 100, 2))
df_vax['Vaccine_Doses'].value_counts().sort_index()

Vaccinated %: 3.43

Vaccine_Doses
0.0    16205
1.0      107
2.0      354
3.0      106
4.0        8
Name: count, dtype: int64

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

df_raw = pd.read_excel('/content/covid.xlsx')

df_raw.to_csv(
    '/content/covid_raw.csv',
    index=False,
    encoding='utf-8-sig'
)

print(df_raw.shape)

In [ ]:
# 1️⃣ خواندن داده خام CSV
df = pd.read_csv('/content/covid_raw.csv')

print("شکل دیتاست:")
print(df.shape)

شکل دیتاست:
(16783, 163)

/tmp/ipython-input-3945028644.py:2: DtypeWarning: Columns (6,18,21,22,30,31,33,47,48,50,51,52,53,54,56,57,61,64,65,66,69,74,75,76,77,78,79,80,81,82,83,85,86,87,88,89,90,93,95,96,100,103,106,107,108,109,110,111,112,113,114,115,117,118,119,120,121,122,123,124,126,127,128,129,130,132,133,138,142,144,150,155,156) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/covid_raw.csv')

In [ ]:
# 2️⃣ لیست ستون‌ها و نوع داده
print("\nاطلاعات کلی ستون‌ها:")
print(df.info())

اطلاعات کلی ستون‌ها:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16783 entries, 0 to 16782
Columns: 163 entries, پاسخنامه to تاریخ اتمام
dtypes: float64(2), object(161)
memory usage: 20.9+ MB
None

In [ ]:
# 3️⃣ تعداد مقادیر خالی هر ستون
missing = df.isna().sum().sort_values(ascending=False)

print("\n۱۰ ستون با بیشترین مقدار Missing:")
print(missing.head(10))

۱۰ ستون با بیشترین مقدار Missing:
Unnamed: 54     16782
Unnamed: 114    16782
Unnamed: 109    16781
Unnamed: 107    16781
Unnamed: 112    16781
Unnamed: 110    16780
Unnamed: 64     16779
Unnamed: 52     16779
Unnamed: 65     16778
Unnamed: 111    16777
dtype: int64

In [ ]:
# 4️⃣ درصد Missing هر ستون
missing_percent = (missing / len(df)) * 100

print("\n۱۰ ستون با بیشترین درصد Missing:")
print(missing_percent.head(10))

۱۰ ستون با بیشترین درصد Missing:
Unnamed: 54     99.994042
Unnamed: 114    99.994042
Unnamed: 109    99.988083
Unnamed: 107    99.988083
Unnamed: 112    99.988083
Unnamed: 110    99.982125
Unnamed: 64     99.976166
Unnamed: 52     99.976166
Unnamed: 65     99.970208
Unnamed: 111    99.964250
dtype: float64

In [ ]:
# 5️⃣ شناسایی ستون‌های مشکوک (خیلی خالی)
high_missing_cols = missing_percent[missing_percent > 70]

print("\nستون‌هایی با بیش از 70٪ داده خالی:")
print(high_missing_cols)

ستون‌هایی با بیش از 70٪ داده خالی:
Unnamed: 54          99.994042
Unnamed: 114         99.994042
Unnamed: 109         99.988083
Unnamed: 107         99.988083
Unnamed: 112         99.988083
                       ...
سابقه واکسیناسیون    80.486206
Unnamed: 98          79.425609
Unnamed: 58          77.709587
Unnamed: 97          74.784008
Unnamed: 45          70.916999
Length: 131, dtype: float64

In [ ]:
# 6️⃣ بررسی ستون‌های Unnamed (فقط گزارش)
unnamed_cols = [c for c in df.columns if c.startswith('Unnamed')]
print("\nتعداد ستون‌های Unnamed:")
print(len(unnamed_cols))

تعداد ستون‌های Unnamed:
147

In [ ]:
df.columns.tolist()

['پاسخنامه',
 'شناسه پاسخ دهنده',
 'نام کاربری تکمیل کننده',
 'کد پذیرش',
 'کد داده',
 'شکایت اصلی',
 'Unnamed: 6',
 'بیماری فعلی (Present illness)',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Unnamed: 33',
 'Unnamed: 34',
 'Unnamed: 35',
 'تاریخچه بیماری های قبلی (PMH)',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41',
 'Unnamed: 42',
 'Unnamed: 43',
 'Unnamed: 44',
 'Unnamed: 45',
 'Unnamed: 46',
 'Unnamed: 47',
 'Unnamed: 48',
 'Unnamed: 49',
 'Unnamed: 50',
 'Unnamed: 51',
 'Unnamed: 52',
 'Unnamed: 53',
 'Unnamed: 54',
 'Unnamed: 55',
 'Unnamed: 56',
 'Unnamed: 57',
 'Unnamed: 58',
 'Unnamed: 59',
 'Unnamed: 60',
 'Unnamed: 61',
 'Unnamed: 62',
 'Unnamed: 63',
 'Unnamed: 64',
 'Unnamed: 65',
 'Unnamed: 66',
 'Unnamed: 67',
 'سوابق مرتبط با کووید 19',
 'Unnamed: 69',
 'Unnamed: 70',
 'Unnamed: 71',
 'Unnamed: 72',
 'Unnamed: 73',
 'داروهای در حال مصرف و سوابق اعتیاد',
 'Unnamed: 75',
 'Unnamed: 76',
 'Unnamed: 77',
 'Unnamed: 78',
 'Unnamed: 79',
 'Unnamed: 80',
 'Unnamed: 81',
 'Unnamed: 82',
 'Unnamed: 83',
 'Unnamed: 84',
 'Unnamed: 85',
 'Unnamed: 86',
 'Unnamed: 87',
 'Unnamed: 88',
 'Unnamed: 89',
 'Unnamed: 90',
 'Unnamed: 91',
 'Unnamed: 92',
 'Unnamed: 93',
 'Unnamed: 94',
 'Unnamed: 95',
 'Unnamed: 96',
 'Unnamed: 97',
 'Unnamed: 98',
 'سابقه واکسیناسیون',
 'Unnamed: 100',
 'Unnamed: 101',
 'سوابق فامیلی',
 'Unnamed: 103',
 'Unnamed: 104',
 'Unnamed: 105',
 'Unnamed: 106',
 'Unnamed: 107',
 'Unnamed: 108',
 'Unnamed: 109',
 'Unnamed: 110',
 'Unnamed: 111',
 'Unnamed: 112',
 'Unnamed: 113',
 'Unnamed: 114',
 'Unnamed: 115',
 'Unnamed: 116',
 'Unnamed: 117',
 'معاینات بالینی',
 'Unnamed: 119',
 'Unnamed: 120',
 'Unnamed: 121',
 'Unnamed: 122',
 'Unnamed: 123',
 'Unnamed: 124',
 'Unnamed: 125',
 'Unnamed: 126',
 'Unnamed: 127',
 'Unnamed: 128',
 'Unnamed: 129',
 'Unnamed: 130',
 'Unnamed: 131',
 'Unnamed: 132',
 'Unnamed: 133',
 'Unnamed: 134',
 'Unnamed: 135',
 'Unnamed: 136',
 'Unnamed: 137',
 'Unnamed: 138',
 'Unnamed: 139',
 'Unnamed: 140',
 'Unnamed: 141',
 'Unnamed: 142',
 'Unnamed: 143',
 'Unnamed: 144',
 'مشاوره های بیمار',
 'Unnamed: 146',
 'Unnamed: 147',
 'Unnamed: 148',
 'Unnamed: 149',
 'Unnamed: 150',
 'Unnamed: 151',
 'Unnamed: 152',
 'Unnamed: 153',
 'Unnamed: 154',
 'Unnamed: 155',
 'Unnamed: 156',
 'Unnamed: 157',
 'Unnamed: 158',
 'Unnamed: 159',
 'Unnamed: 160',
 'تاریخ شروع',
 'تاریخ اتمام']

In [ ]:
clinical_cols = ['معاینات بالینی'] + [f'Unnamed: {i}' for i in range(119, 145)]
df[clinical_cols].head(10)
#این کار:

#۱۰ بیمار اول رو نشون می‌ده

#می‌فهمیم هر ستون:عددیه؟ مثلاً SpO2)متنیه؟ (مثلاً «طبیعی / غیرطبیعی»)بله/خیر؟

,معاینات بالینی,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,...,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144
0,فشار خون سیستولیک,فشار خون دیاستولیک,تعداد ضربان قلب,تعداد تنفس,درجه حرارت (به سانتیگراد),درصد اشباع اکسیژن خون (بدون دریافت اکسیژن),درصد اشباع اکسژن خون(با دریافت اکسیژن),میزان هوشیاری,مشاهدات,NaN,...,NaN,NaN,NaN,NaN,NaN,سایر نکات معاینه(در صورتی که در معاینه بالینی ...,آیا بیمار بستری در ICU داشته است؟,مدت زمان بستری در ICU: (روز),آیا بیمار اینتوبه شده است؟,اگر بیمار اینتوبه شده است:\nچند روز اینتوبه بو...
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,کنژکتیویت,دیسترس تنفسی,...,کراکل دو طرفه,کاهش صدا یک طرفه,کاهش صدا دوطرفه,ویز یک طرفه,ویز دو طرفه,NaN,NaN,NaN,NaN,NaN
2,120,80,86,16,37.1,88,NaN,هوشیار,NaN,NaN,...,کراکل دو طرفه,NaN,NaN,NaN,NaN,ادم اندام تحتانی,خیر,NaN,خیر,NaN
3,116,54,62,16,36.4,96,NaN,هوشیار,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,خیر,NaN,خیر,NaN
4,130,75,76,NaN,NaN,96,NaN,هوشیار,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,خیر,NaN,خیر,NaN
5,138,92,69,18,37,87,95,هوشیار,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,خلط خونی,خیر,NaN,خیر,NaN
6,135,95,72,NaN,NaN,98,NaN,هوشیار,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,خیر,NaN,خیر,NaN
7,120,80,74,30,NaN,81,99,هوشیار,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,خیر,NaN,خیر,NaN
8,100,70,83,19,NaN,92,99,هوشیار,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,بلی,2,NaN,NaN
9,125,80,NaN,110,NaN,NaN,95,هوشیار,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
(df[clinical_cols].isnull().mean() * 100).sort_values()

Unnamed: 123      11.970446
Unnamed: 120      26.217005
معاینات بالینی    28.302449
Unnamed: 119      28.838706
Unnamed: 125      30.751356
Unnamed: 141      33.313472
Unnamed: 122      34.183400
Unnamed: 143      36.846809
Unnamed: 121      50.795448
Unnamed: 132      63.772865
Unnamed: 124      64.011202
Unnamed: 133      69.492939
Unnamed: 142      94.119049
Unnamed: 135      94.381219
Unnamed: 140      97.747721
Unnamed: 139      98.057558
Unnamed: 127      98.337604
Unnamed: 134      98.623607
Unnamed: 144      98.665316
Unnamed: 137      99.130072
Unnamed: 136      99.231365
Unnamed: 131      99.559078
Unnamed: 138      99.713996
Unnamed: 126      99.713996
Unnamed: 130      99.791456
Unnamed: 129      99.839123
Unnamed: 128      99.934457
dtype: float64

ستون‌هایی با بیش از ۹۰٪ داده مفقود حذف شدند، زیرا فاقد ارزش آماری برای مدل‌سازی بودند

In [ ]:
good_cols = [
    'معاینات بالینی',
    'Unnamed: 123',
    'Unnamed: 120',
    'Unnamed: 119',
    'Unnamed: 125',
    'Unnamed: 141',
    'Unnamed: 122',
    'Unnamed: 143',
    'Unnamed: 121',
    'Unnamed: 132',
    'Unnamed: 124',
    'Unnamed: 133'
]

df[good_cols].head(15)

,معاینات بالینی,Unnamed: 123,Unnamed: 120,Unnamed: 119,Unnamed: 125,Unnamed: 141,Unnamed: 122,Unnamed: 143,Unnamed: 121,Unnamed: 132,Unnamed: 124,Unnamed: 133
0,فشار خون سیستولیک,درصد اشباع اکسیژن خون (بدون دریافت اکسیژن),تعداد ضربان قلب,فشار خون دیاستولیک,میزان هوشیاری,آیا بیمار بستری در ICU داشته است؟,درجه حرارت (به سانتیگراد),آیا بیمار اینتوبه شده است؟,تعداد تنفس,NaN,درصد اشباع اکسژن خون(با دریافت اکسیژن),سمع ریه
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,هیچکدام,NaN,نرمال
2,120,88,86,80,هوشیار,خیر,37.1,خیر,16,هیچکدام,NaN,NaN
3,116,96,62,54,هوشیار,خیر,36.4,خیر,16,هیچکدام,NaN,NaN
4,130,96,76,75,هوشیار,خیر,NaN,خیر,NaN,NaN,NaN,NaN
5,138,87,69,92,هوشیار,خیر,37,خیر,18,هیچکدام,95,نرمال
6,135,98,72,95,هوشیار,خیر,NaN,خیر,NaN,NaN,NaN,NaN
7,120,81,74,80,هوشیار,خیر,NaN,خیر,30,NaN,99,NaN
8,100,92,83,70,هوشیار,بلی,NaN,NaN,19,NaN,99,NaN
9,125,NaN,NaN,80,هوشیار,NaN,NaN,NaN,110,NaN,95,NaN
10,130,76,104,70,هوشیار,NaN,NaN,NaN,NaN,NaN,98,NaN
11,75,97,160,50,هوشیار,NaN,38,NaN,64,NaN,NaN,NaN
12,NaN,88,105,NaN,هوشیار,NaN,36,خیر,NaN,NaN,NaN,NaN
13,110,NaN,102,80,هوشیار,NaN,NaN,NaN,18,NaN,93,NaN
14,160,85,95,80,هوشیار,خیر,NaN,خیر,48,NaN,95,NaN

In [ ]:
# استخراج بخش بالینی
clinical_cols = ['معاینات بالینی'] + [f'Unnamed: {i}' for i in range(119, 145)]
df_clinical = df[clinical_cols].copy()

# نام‌گذاری
rename_map = {
    'معاینات بالینی': 'BP_Systolic',
    'Unnamed: 119': 'BP_Diastolic',
    'Unnamed: 120': 'Heart_Rate',
    'Unnamed: 121': 'Respiratory_Rate',
    'Unnamed: 122': 'Temperature',
    'Unnamed: 123': 'SpO2_No_O2',
    'Unnamed: 124': 'SpO2_With_O2',
    'Unnamed: 125': 'Consciousness',
    'Unnamed: 141': 'ICU_Admission',
    'Unnamed: 143': 'Intubation',
    'Unnamed: 132': 'Observations',
    'Unnamed: 133': 'Lung_Auscultation',
}
df_clinical.rename(columns=rename_map, inplace=True)

In [ ]:
# 4️⃣ حذف ردیف‌هایی که در واقع هدر هستن (مثل ردیف 0 و 1 در نمونه‌ها)
# این ردیف‌ها شامل متن‌هایی مثل "فشار خون سیستولیک" یا "درصد اشباع اکسیژن" هستن
df_clinical = df_clinical[
    ~df_clinical['BP_Systolic'].astype(str).str.contains('فشار خون|سیستولیک', na=True)
]
df_clinical = df_clinical[
    ~df_clinical['SpO2_No_O2'].astype(str).str.contains('اشباع|اکسیژن|درصد', na=True)
]
df_clinical = df_clinical[
    ~df_clinical['Heart_Rate'].astype(str).str.contains('ضربان|قلب', na=True)
]

# ریست ایندکس بعد از حذف
df_clinical.reset_index(drop=True, inplace=True)

print(f"تعداد رکورد بعد از حذف هدرهای اشتباه: {len(df_clinical)}")

تعداد رکورد بعد از حذف هدرهای اشتباه: 16782

In [ ]:
# 5️⃣ تمیز کردن مقادیر متنی قبل از تبدیل به عدد
numeric_cols = ['BP_Systolic', 'BP_Diastolic', 'Heart_Rate',
                'Respiratory_Rate', 'Temperature',
                'SpO2_No_O2', 'SpO2_With_O2']

for col in numeric_cols:
    df_clinical[col] = (
        df_clinical[col]
        .astype(str)
        .str.strip()
        .str.replace('%', '', regex=False)
        .str.replace(r'\.$', '', regex=True)  # حذف نقطه آخر مثل 37.
        .replace('nan', np.nan)
    )
# 6️⃣ تبدیل به عددی (هر چیزی که نشد → NaN)
df_clinical[numeric_cols] = df_clinical[numeric_cols].apply(pd.to_numeric, errors='coerce')

# 7️⃣ تمیز کردن ستون‌های کتگوریکال
cat_cols = ['Consciousness', 'ICU_Admission', 'Intubation',
            'Observations', 'Lung_Auscultation']

for col in cat_cols:
    df_clinical[col] = (
        df_clinical[col]
        .astype(str)
        .str.strip()
        .str.lower()
        .replace('nan', np.nan)
    )

In [ ]:
# 8️⃣ پر کردن هوشمند مقادیر گمشده

# اول: عددی‌ها با KNN Imputer (بهترین روش برای داده‌های بالینی)
print("در حال اجرای KNN Imputer برای فیچرهای عددی...")
knn_imputer = KNNImputer(n_neighbors=5, weights='uniform')
df_clinical[numeric_cols] = knn_imputer.fit_transform(df_clinical[numeric_cols])

# دوم: کتگوریکال با شایع‌ترین مقدار (mode)
for col in cat_cols:
    mode_val = df_clinical[col].mode()[0] if not df_clinical[col].mode().empty else 'unknown'
    df_clinical[col].fillna(mode_val, inplace=True)

در حال اجرای KNN Imputer برای فیچرهای عددی...

/tmp/ipython-input-2101037829.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clinical[col].fillna(mode_val, inplace=True)

In [ ]:
# 9️⃣ نتیجه نهایی
print("\n✅ پیش‌پردازش کامل شد!")
print("شکل نهایی دیتافریم بالینی:", df_clinical.shape)
print("تعداد NaN باقی‌مانده در هر ستون:")
print(df_clinical.isna().sum())

print("\n📊 آمار توصیفی فیچرهای عددی:")
display(df_clinical[numeric_cols].describe())

print("\n👀 نمونه ۱۰ رکورد اول:")
display(df_clinical.head(10))

print("\n🎯 حالا قسمت علائم بالینی دیتاست کاملاً تمیز و آماده است :")

✅ پیش‌پردازش کامل شد!
شکل نهایی دیتافریم بالینی: (16782, 12)
تعداد NaN باقی‌مانده در هر ستون:
BP_Systolic          0
BP_Diastolic         0
Heart_Rate           0
Respiratory_Rate     0
Temperature          0
SpO2_No_O2           0
SpO2_With_O2         0
Consciousness        0
ICU_Admission        0
Intubation           0
Observations         0
Lung_Auscultation    0
dtype: int64

📊 آمار توصیفی فیچرهای عددی:

,BP_Systolic,BP_Diastolic,Heart_Rate,Respiratory_Rate,Temperature,SpO2_No_O2,SpO2_With_O2
count,16782.000000,16782.000000,16782.000000,16782.000000,16782.000000,16782.000000,16782.000000
mean,123.025396,76.671105,88.256246,20.052967,37.681406,92.734611,96.448201
std,16.709799,10.663416,16.628577,13.911426,28.664926,125.073563,3.535566
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,115.000000,70.000000,80.000000,17.000000,36.500000,89.000000,95.452890
50%,122.645695,76.625691,87.400000,18.000000,36.950000,92.807622,97.000000
75%,130.000000,80.000000,94.400000,20.400000,37.360000,95.000000,98.200000
max,240.000000,150.000000,784.000000,1616.000000,3605.000000,9694.000000,109.000000

👀 نمونه ۱۰ رکورد اول:

,BP_Systolic,BP_Diastolic,Heart_Rate,Respiratory_Rate,Temperature,SpO2_No_O2,SpO2_With_O2,Consciousness,ICU_Admission,Intubation,Observations,Lung_Auscultation
0,122.645695,76.625691,88.143757,19.683662,37.631607,92.807622,95.45289,هوشیار,خیر,خیر,هیچکدام,نرمال
1,120.000000,80.000000,86.000000,16.000000,37.100000,88.000000,94.80000,هوشیار,خیر,خیر,هیچکدام,نرمال
2,116.000000,54.000000,62.000000,16.000000,36.400000,96.000000,98.20000,هوشیار,خیر,خیر,هیچکدام,نرمال
3,130.000000,75.000000,76.000000,25.200000,47.700000,96.000000,98.80000,هوشیار,خیر,خیر,هیچکدام,نرمال
4,138.000000,92.000000,69.000000,18.000000,37.000000,87.000000,95.00000,هوشیار,خیر,خیر,هیچکدام,نرمال
5,135.000000,95.000000,72.000000,18.600000,36.900000,98.000000,98.60000,هوشیار,خیر,خیر,هیچکدام,نرمال
6,120.000000,80.000000,74.000000,30.000000,38.300000,81.000000,99.00000,هوشیار,خیر,خیر,هیچکدام,نرمال
7,100.000000,70.000000,83.000000,19.000000,37.460000,92.000000,99.00000,هوشیار,بلی,خیر,هیچکدام,نرمال
8,125.000000,80.000000,83.200000,110.000000,36.440000,88.200000,95.00000,هوشیار,خیر,خیر,هیچکدام,نرمال
9,130.000000,70.000000,104.000000,28.800000,37.500000,76.000000,98.00000,هوشیار,خیر,خیر,هیچکدام,نرمال

🎯 حالا دیتاست کاملاً تمیز و آماده است برای:
   • تعریف Target شدت بیماری
   • ویژوال‌سازی
   • مدل‌سازی ML

In [ ]:
# =========================
# 1) انتخاب بازه ستون‌های Present Illness
# =========================
# بر اساس ساختار فایل (Unnamed:6 تا Unnamed:35)
symptom_cols = ['Unnamed: 6'] + list(df_raw.columns[7:36])
df_symptoms_raw = df_raw[symptom_cols].copy()

# =========================
# 2) حذف ردیف‌های هدر متنی
# =========================
# ردیف‌های 0،1،2 شامل توضیحات فرم هستند
df_symptoms = df_symptoms_raw.iloc[3:].reset_index(drop=True)

# =========================
# 3) مپینگ صحیح و تأییدشده علائم
# =========================
symptom_rename_map = {
    'Unnamed: 6':  'Onset_Days',        # زمان شروع علائم (عددی – جدا نگه داشته می‌شود)

    'Unnamed: 8':  'Fever',              # تب
    'Unnamed: 9':  'Myalgia',            # بدن درد
    'Unnamed: 10': 'Chills',             # لرز
    'Unnamed: 11': 'Fatigue',            # ضعف / بی‌حالی
    'Unnamed: 12': 'Sweating',           # تعریق
    'Unnamed: 13': 'Anorexia',           # بی‌اشتهایی
    'Unnamed: 14': 'Sore_Throat',        # گلودرد
    'Unnamed: 15': 'Sneezing',           # عطسه
    'Unnamed: 16': 'Cough',              # سرفه
    'Unnamed: 17': 'Dyspnea',            # تنگی نفس
    'Unnamed: 18': 'Eye_Burning',        # سوزش چشم
    'Unnamed: 19': 'Anosmia',            # کاهش بویایی
    'Unnamed: 20': 'Rhinorrhea',         # آبریزش بینی
    'Unnamed: 21': 'Voice_Change',       # تغییر صدا
    'Unnamed: 22': 'Nasal_Congestion',   # گرفتگی بینی
    'Unnamed: 23': 'Ageusia',            # کاهش چشایی
    'Unnamed: 24': 'Chest_Pain',         # درد قفسه سینه
    'Unnamed: 25': 'Palpitations',       # تپش قلب
    'Unnamed: 26': 'Nausea',              # تهوع
    'Unnamed: 27': 'Vomiting',           # استفراغ
    'Unnamed: 28': 'Abdominal_Pain',     # درد شکم
    'Unnamed: 29': 'Diarrhea',           # اسهال
    'Unnamed: 32': 'Depression',         # افسردگی
    'Unnamed: 33': 'Sleep_Disorder',     # اختلال خواب
    'Unnamed: 34': 'Headache',           # سردرد
}

# =========================
# 4) باینری‌سازی علائم
# =========================
# هر مقدار غیر NaN → علامت وجود دارد
df_symptoms_binary = df_symptoms.notna().astype(int)

# اعمال نام‌های معنادار
df_symptoms_binary.rename(columns=symptom_rename_map, inplace=True)

# =========================
# 5) جداسازی onset از علائم
# =========================
symptom_cols_final = [
    col for col in df_symptoms_binary.columns
    if col in symptom_rename_map.values() and col != 'Onset_Days'
]

df_present_illness = df_symptoms_binary[symptom_cols_final].copy()

# =========================
# 6) خروجی‌ها
# =========================
print("📐 شکل دیتافریم علائم فعلی:")
print(df_present_illness.shape)

print("\n🔍 نمونه ۱۰ رکورد:")
display(df_present_illness.head(10))

print("\n📊 شیوع علائم (درصد بیماران):")
prevalence = df_present_illness.mean().sort_values(ascending=False) * 100
display(prevalence.round(2))

📐 شکل دیتافریم علائم فعلی:
(16780, 25)

🔍 نمونه ۱۰ رکورد:

,Fever,Myalgia,Chills,Fatigue,Sweating,Anorexia,Sore_Throat,Sneezing,Cough,Dyspnea,...,Ageusia,Chest_Pain,Palpitations,Nausea,Vomiting,Abdominal_Pain,Diarrhea,Depression,Sleep_Disorder,Headache
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
4,0,0,1,0,0,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,0,0,1,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,1,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

📊 شیوع علائم (درصد بیماران):

Cough               56.70
Dyspnea             52.36
Myalgia             35.52
Chills              35.50
Fever               34.93
Sweating            16.54
Headache            15.60
Nausea              15.38
Vomiting            14.95
Diarrhea             7.34
Chest_Pain           6.06
Anorexia             5.60
Sore_Throat          4.99
Abdominal_Pain       4.58
Rhinorrhea           3.70
Fatigue              3.37
Anosmia              2.34
Ageusia              1.66
Nasal_Congestion     0.88
Sneezing             0.85
Voice_Change         0.57
Palpitations         0.36
Eye_Burning          0.23
Sleep_Disorder       0.15
Depression           0.07
dtype: float64

'تاریخچه بیماری های قبلی (PMH)'
'Unnamed: 37' تا حدود 'Unnamed: 66'
این بخش معمولاً شامل:

دیابت

فشار خون

بیماری قلبی

بیماری ریوی

کلیوی

کبدی

سرطان

نقص ایمنی

بارداری

بیماری عصبی

چاقی

(همه به‌صورت checkbox → سلول غیرخالی)

In [ ]:
# =========================
# 1) انتخاب ستون‌های PMH
# =========================
pmh_cols = ['تاریخچه بیماری های قبلی (PMH)'] + list(df_raw.columns[37:67])
df_pmh_raw = df_raw[pmh_cols].copy()

# حذف ردیف‌های توضیحی
df_pmh = df_pmh_raw.iloc[3:].reset_index(drop=True)

In [ ]:
# بررسی محتوای واقعی هر ستون
for col in df_pmh.columns:
    print(col)
    print(df_pmh[col].value_counts(dropna=False).head(5))
    print('-'*40)

تاریخچه بیماری های قبلی (PMH)
تاریخچه بیماری های قبلی (PMH)
بله    8856
خیر    4414
NaN    3510
Name: count, dtype: int64
----------------------------------------
Unnamed: 37
Unnamed: 37
NaN      16424
سرطان      356
Name: count, dtype: int64
----------------------------------------
Unnamed: 38
Unnamed: 38
NaN          16636
پیوند عضو      144
Name: count, dtype: int64
----------------------------------------
Unnamed: 39
Unnamed: 39
NaN             16317
نارسایی کلیه      463
Name: count, dtype: int64
----------------------------------------
Unnamed: 40
Unnamed: 40
NaN       16577
دیالیز      203
Name: count, dtype: int64
----------------------------------------
Unnamed: 41
Unnamed: 41
NaN        16430
لنفوم         28
پروستات       19
کولون         15
سینه          13
Name: count, dtype: int64
----------------------------------------
Unnamed: 42
Unnamed: 42
NaN            16631
کلیه             120
کبد               14
مغز استخوان        4
پیوند کلیه         3
Name: count, dtype: int64
----------------------------------------
Unnamed: 43
Unnamed: 43
NaN    16362
آسم      418
Name: count, dtype: int64
----------------------------------------
Unnamed: 44
Unnamed: 44
NaN                  16345
بیماری مزمن تنفسی      435
Name: count, dtype: int64
----------------------------------------
Unnamed: 45
Unnamed: 45
NaN        11901
فشارخون     4879
Name: count, dtype: int64
----------------------------------------
Unnamed: 46
Unnamed: 46
NaN          15678
سکته قلبی     1102
Name: count, dtype: int64
----------------------------------------
Unnamed: 47
Unnamed: 47
NaN                 16696
بیماری دریچه قلب       84
Name: count, dtype: int64
----------------------------------------
Unnamed: 48
Unnamed: 48
NaN            16247
نارسایی قلب      533
Name: count, dtype: int64
----------------------------------------
Unnamed: 49
Unnamed: 49
NaN                 15794
تریگلیسیرید بالا      986
Name: count, dtype: int64
----------------------------------------
Unnamed: 50
Unnamed: 50
NaN             15252
کلسترول بالا     1528
Name: count, dtype: int64
----------------------------------------
Unnamed: 51
Unnamed: 51
NaN                    16755
بیماری التهابی روده       25
Name: count, dtype: int64
----------------------------------------
Unnamed: 52
Unnamed: 52
NaN    16777
IBS        3
Name: count, dtype: int64
----------------------------------------
Unnamed: 53
Unnamed: 53
NaN            16749
هپاتیت مزمن       31
Name: count, dtype: int64
----------------------------------------
Unnamed: 54
Unnamed: 54
NaN    16780
Name: count, dtype: int64
----------------------------------------
Unnamed: 55
Unnamed: 55
NaN          16456
سکته مغزی      324
Name: count, dtype: int64
----------------------------------------
Unnamed: 56
Unnamed: 56
NaN     16571
تشنج      209
Name: count, dtype: int64
----------------------------------------
Unnamed: 57
Unnamed: 57
NaN             16491
دیابت تیپ یک      289
Name: count, dtype: int64
----------------------------------------
Unnamed: 58
Unnamed: 58
NaN             13041
دیابت تیپ دو     3739
Name: count, dtype: int64
----------------------------------------
Unnamed: 59
Unnamed: 59
NaN                15950
کم کاری تیروئید      830
Name: count, dtype: int64
----------------------------------------
Unnamed: 60
Unnamed: 60
NaN               16737
پرکاری تیروئید       43
Name: count, dtype: int64
----------------------------------------
Unnamed: 61
Unnamed: 61
NaN             16071
مصرف انسولین      709
Name: count, dtype: int64
----------------------------------------
Unnamed: 62
Unnamed: 62
NaN                 16540
آرتریت روماتوئید      240
Name: count, dtype: int64
----------------------------------------
Unnamed: 63
Unnamed: 63
NaN      16736
لوپوس       44
Name: count, dtype: int64
----------------------------------------
Unnamed: 64
Unnamed: 64
NaN     16777
بهجت        3
Name: count, dtype: int64
----------------------------------------
Unnamed: 65
Unnamed: 65
NaN      16776
شوگرن        4
Name: count, dtype: int64
----------------------------------------
Unnamed: 66
Unnamed: 66
NaN    16628
+A        47
+O        39
+B        27
-B        10
Name: count, dtype: int64
----------------------------------------

تاریخچه بیماری های قبلی (PMH)
بله / خیر

In [ ]:
# =========================
# PMH - Past Medical History
# =========================

# 1) انتخاب ستون‌های PMH
pmh_cols = list(df_raw.columns[37:67])
df_pmh_raw = df_raw[pmh_cols].copy()

# حذف ردیف‌های متنی
df_pmh = df_pmh_raw.iloc[3:].reset_index(drop=True)

# 2) باینری‌سازی (presence-based)
df_pmh_binary = df_pmh.notna().astype(int)

# 3) مپینگ نهایی
pmh_rename_map = {
    'Unnamed: 37': 'Cancer',
    'Unnamed: 38': 'Organ_Transplant',
    'Unnamed: 39': 'Chronic_Kidney_Disease',
    'Unnamed: 40': 'Dialysis',
    'Unnamed: 41': 'Cancer_Type',
    'Unnamed: 42': 'Solid_Organ_Transplant',
    'Unnamed: 43': 'Asthma',
    'Unnamed: 44': 'Chronic_Respiratory_Disease',
    'Unnamed: 45': 'Hypertension',
    'Unnamed: 46': 'Myocardial_Infarction',
    'Unnamed: 47': 'Valvular_Heart_Disease',
    'Unnamed: 48': 'Heart_Failure',
    'Unnamed: 49': 'Hypertriglyceridemia',
    'Unnamed: 50': 'Hypercholesterolemia',
    'Unnamed: 51': 'IBD',
    'Unnamed: 52': 'IBS',
    'Unnamed: 53': 'Chronic_Hepatitis',
    'Unnamed: 55': 'Stroke',
    'Unnamed: 56': 'Seizure',
    'Unnamed: 57': 'Diabetes_Type1',
    'Unnamed: 58': 'Diabetes_Type2',
    'Unnamed: 59': 'Hypothyroidism',
    'Unnamed: 60': 'Hyperthyroidism',
    'Unnamed: 61': 'Insulin_Use',
    'Unnamed: 62': 'Rheumatoid_Arthritis',
    'Unnamed: 63': 'Lupus',
    'Unnamed: 64': 'Behcet',
    'Unnamed: 65': 'Sjogren',
}

df_pmh_binary.rename(columns=pmh_rename_map, inplace=True)

# 4) نگه‌داری فقط ستون‌های معتبر
df_pmh_final = df_pmh_binary[list(pmh_rename_map.values())]

# 5) خروجی تحلیلی
print("📐 شکل دیتافریم PMH:", df_pmh_final.shape)

print("\n🔍 نمونه داده‌ها:")
display(df_pmh_final.head(10))

print("\n📊 شیوع بیماری‌های زمینه‌ای (%):")
display((df_pmh_final.mean() * 100).sort_values(ascending=False).round(2))

📐 شکل دیتافریم PMH: (16780, 28)

🔍 نمونه داده‌ها:

,Cancer,Organ_Transplant,Chronic_Kidney_Disease,Dialysis,Cancer_Type,Solid_Organ_Transplant,Asthma,Chronic_Respiratory_Disease,Hypertension,Myocardial_Infarction,...,Seizure,Diabetes_Type1,Diabetes_Type2,Hypothyroidism,Hyperthyroidism,Insulin_Use,Rheumatoid_Arthritis,Lupus,Behcet,Sjogren
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0

📊 شیوع بیماری‌های زمینه‌ای (%):

Hypertension                   29.08
Diabetes_Type2                 22.28
Hypercholesterolemia            9.11
Myocardial_Infarction           6.57
Hypertriglyceridemia            5.88
Hypothyroidism                  4.95
Insulin_Use                     4.23
Heart_Failure                   3.18
Chronic_Kidney_Disease          2.76
Chronic_Respiratory_Disease     2.59
Asthma                          2.49
Cancer                          2.12
Cancer_Type                     2.09
Stroke                          1.93
Diabetes_Type1                  1.72
Rheumatoid_Arthritis            1.43
Seizure                         1.25
Dialysis                        1.21
Solid_Organ_Transplant          0.89
Organ_Transplant                0.86
Valvular_Heart_Disease          0.50
Lupus                           0.26
Hyperthyroidism                 0.26
Chronic_Hepatitis               0.18
IBD                             0.15
Sjogren                         0.02
IBS                             0.02
Behcet                          0.02
dtype: float64

«ما از داده خام بیمارستانی، یک لایه Risk Profile بالینی قابل تفسیر ساختیم که مستقیماً در پیش‌بینی شدت کووید استفاده می‌شود.»

'سوابق مرتبط با کووید 19'
'Unnamed: 69' تا 'Unnamed: 73'

این بخش معمولاً شامل:

سابقه ابتلای قبلی

بستری قبلی

ICU

اینتوباسیون

مرگ در اطرافیان (گاهی

In [ ]:
# =========================
# COVID History
# =========================

# 1) انتخاب ستون‌ها
covid_hist_cols = list(df_raw.columns[69:74])
df_covid_hist_raw = df_raw[covid_hist_cols].copy()

# حذف ردیف‌های متنی
df_covid_hist = df_covid_hist_raw.iloc[3:].reset_index(drop=True)

# 2) باینری‌سازی (presence-based)
df_covid_hist_binary = df_covid_hist.notna().astype(int)

# 3) Rename ستون‌ها
covid_hist_rename_map = {
    'Unnamed: 69': 'Previous_COVID_Infection',
    'Unnamed: 70': 'Previous_Hospitalization',
    'Unnamed: 71': 'Previous_ICU',
    'Unnamed: 72': 'Previous_Intubation',
    'Unnamed: 73': 'COVID_Related_Death_Family',
}

df_covid_hist_binary.rename(columns=covid_hist_rename_map, inplace=True)

# 4) نگه‌داری فقط ستون‌های معتبر
covid_hist_final = df_covid_hist_binary[list(covid_hist_rename_map.values())]

# 5) خروجی تحلیلی
print("📐 شکل دیتافریم COVID History:", covid_hist_final.shape)

print("\n🔍 نمونه داده‌ها:")
display(covid_hist_final.head(10))

print("\n📊 شیوع سوابق مرتبط با کووید (%):")
display((covid_hist_final.mean() * 100).sort_values(ascending=False).round(2))

📐 شکل دیتافریم COVID History: (16780, 5)

🔍 نمونه داده‌ها:

,Previous_COVID_Infection,Previous_Hospitalization,Previous_ICU,Previous_Intubation,COVID_Related_Death_Family
0,1,0,1,1,1
1,1,0,1,1,1
2,0,0,0,0,0
3,0,0,0,0,0
4,0,0,0,0,0
5,0,0,0,0,0
6,0,0,0,0,0
7,0,0,0,0,0
8,0,0,0,0,0
9,0,1,0,0,0

📊 شیوع سوابق مرتبط با کووید (%):

COVID_Related_Death_Family    4.98
Previous_Intubation           4.30
Previous_Hospitalization      3.36
Previous_COVID_Infection      1.14
Previous_ICU                  0.60
dtype: float64

«ما تاریخچه مواجهه بیمار با کووید (ابتلای قبلی، بستری، ICU و اینتوباسیون) را استخراج کردیم تا اثر ایمنی نسبی و سابقه بیماری شدید را در مدل لحاظ کنیم.»

داروهای مصرفی (Treatment Features)
'Unnamed: 75' تا 'Unnamed: 84'

این‌ها:

Featureهای پیش‌بینی‌کننده شدت نیستند

بلکه نشانگر تصمیم پزشک هستند
(یعنی data leakage اگر مستقیم در مدل Severity استفاده بشن)

پس استفاده درست:

✔️ برای تحلیل درمان

✔️ برای Explainability

❌ نه برای پیش‌بینی اولیه شدت

In [ ]:
# =========================
# بررسی محتوای Medications & Addiction
# =========================
med_cols = ['داروهای در حال مصرف و سوابق اعتیاد'] + list(df_raw.columns[75:85])
df_med_raw = df_raw[med_cols].copy()
df_med = df_med_raw.iloc[3:].reset_index(drop=True)

for col in df_med.columns:
    print(col)
    print(df_med[col].value_counts(dropna=False).head(5))
    print('-'*40)

داروهای در حال مصرف و سوابق اعتیاد
داروهای در حال مصرف و سوابق اعتیاد
NaN         16500
ناپروکسن      280
Name: count, dtype: int64
----------------------------------------
Unnamed: 75
Unnamed: 75
NaN          16764
دیکلوفناک       16
Name: count, dtype: int64
----------------------------------------
Unnamed: 76
Unnamed: 76
NaN          16755
ایبوبروفن       25
Name: count, dtype: int64
----------------------------------------
Unnamed: 77
Unnamed: 77
NaN     16580
سایر      200
Name: count, dtype: int64
----------------------------------------
Unnamed: 78
Unnamed: 78
NaN             16414
آزیترومایسین      366
Name: count, dtype: int64
----------------------------------------
Unnamed: 79
Unnamed: 79
NaN              16768
داکسی سایکلین       12
Name: count, dtype: int64
----------------------------------------
Unnamed: 80
Unnamed: 80
NaN             16667
لووفلوکساسین      113
Name: count, dtype: int64
----------------------------------------
Unnamed: 81
Unnamed: 81
NaN     15729
سایر     1051
Name: count, dtype: int64
----------------------------------------
Unnamed: 82
Unnamed: 82
NaN            16671
فاویپیراویر      109
Name: count, dtype: int64
----------------------------------------
Unnamed: 83
Unnamed: 83
NaN          16602
اینترفرون      178
Name: count, dtype: int64
----------------------------------------
Unnamed: 84
Unnamed: 84
NaN       14993
کورتون     1787
Name: count, dtype: int64
----------------------------------------

In [ ]:
# =========================
# COVID Treatment Medications
# =========================

# 1) انتخاب ستون‌ها
treat_cols = list(df_raw.columns[74:85])
df_treat_raw = df_raw[treat_cols].copy()

# حذف ردیف‌های متنی
df_treat = df_treat_raw.iloc[3:].reset_index(drop=True)

# 2) باینری‌سازی (دارو مصرف شده یا نه)
df_treat_binary = df_treat.notna().astype(int)

# 3) Rename ستون‌ها (بر اساس خروجی واقعی)
treat_rename_map = {
    'داروهای در حال مصرف و سوابق اعتیاد': 'Naproxen',
    'Unnamed: 75': 'Diclofenac',
    'Unnamed: 76': 'Ibuprofen',
    'Unnamed: 77': 'Other_Meds',
    'Unnamed: 78': 'Azithromycin',
    'Unnamed: 79': 'Doxycycline',
    'Unnamed: 80': 'Levofloxacin',
    'Unnamed: 81': 'Other_Antibiotics',
    'Unnamed: 82': 'Favipiravir',
    'Unnamed: 83': 'Interferon',
    'Unnamed: 84': 'Corticosteroids',
}

df_treat_binary.rename(columns=treat_rename_map, inplace=True)

# 4) نگه‌داری ستون‌های معتبر
df_treat_final = df_treat_binary[list(treat_rename_map.values())]

# 5) خروجی تحلیلی
print("📐 شکل دیتافریم Treatment:", df_treat_final.shape)

print("\n🔍 نمونه داده‌ها:")
display(df_treat_final.head(10))

print("\n📊 شیوع داروهای مصرفی (%):")
display((df_treat_final.mean() * 100).sort_values(ascending=False).round(2))

📐 شکل دیتافریم Treatment: (16780, 11)

🔍 نمونه داده‌ها:

,Naproxen,Diclofenac,Ibuprofen,Other_Meds,Azithromycin,Doxycycline,Levofloxacin,Other_Antibiotics,Favipiravir,Interferon,Corticosteroids
0,0,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,1,0,0,1
3,0,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,1,0,0,1
5,0,0,0,0,0,0,0,0,0,0,1
6,0,0,0,0,0,0,0,1,0,0,0
7,0,0,0,1,0,0,0,0,0,0,1
8,0,0,0,0,0,0,0,1,0,0,1
9,0,0,0,0,0,0,0,0,0,0,1

📊 شیوع داروهای مصرفی (%):

Corticosteroids      10.65
Other_Antibiotics     6.26
Azithromycin          2.18
Naproxen              1.67
Other_Meds            1.19
Interferon            1.06
Levofloxacin          0.67
Favipiravir           0.65
Ibuprofen             0.15
Diclofenac            0.10
Doxycycline           0.07
dtype: float64

«داروهای ثبت‌شده در داده‌ها را به‌عنوان Treatment Indicators در نظر گرفتیم، نه Featureهای پیش‌بینی، تا از Data Leakage جلوگیری کنیم و تحلیل درمان را از تحلیل ریسک جدا کنیم.»

'سابقه واکسیناسیون'
'Unnamed: 100'
'Unnamed: 101'

In [ ]:
# =========================
# بررسی محتوای Vaccination
# =========================
vax_cols = ['سابقه واکسیناسیون', 'Unnamed: 100', 'Unnamed: 101']
df_vax_raw = df_raw[vax_cols].copy()
df_vax = df_vax_raw.iloc[3:].reset_index(drop=True)

for col in df_vax.columns:
    print(col)
    print(df_vax[col].value_counts(dropna=False).head(10))
    print('-'*40)

سابقه واکسیناسیون
سابقه واکسیناسیون
NaN    13507
خیر     2631
بله      642
Name: count, dtype: int64
----------------------------------------
Unnamed: 100
Unnamed: 100
NaN    16205
2        354
1        107
3        106
4          8
Name: count, dtype: int64
----------------------------------------
Unnamed: 101
Unnamed: 101
NaN           16285
سینوفارم        370
برکت             35
استرازنکا        24
سینوفارم         18
آسترازنکا        11
sinopharm         8
اسپوتنیک          4
استرازنیکا        3
نامشخص            3
Name: count, dtype: int64
----------------------------------------

In [ ]:
# =========================
# Vaccination History (Final)
# =========================

# 1) انتخاب ستون‌ها
vax_cols = ['سابقه واکسیناسیون', 'Unnamed: 100', 'Unnamed: 101']
df_vax_raw = df_raw[vax_cols].copy()

# حذف ردیف‌های متنی
df_vax = df_vax_raw.iloc[3:].reset_index(drop=True)

# 2) تعداد دوز (مهم‌ترین ستون)
df_vax['Vaccine_Doses'] = pd.to_numeric(
    df_vax['Unnamed: 100'],
    errors='coerce'
).fillna(0)

# 3) واکسینه شده یا نه (تعریف درست)
df_vax['Vaccinated'] = (df_vax['Vaccine_Doses'] > 0).astype(int)

# 4) ساده‌سازی نوع واکسن (اختیاری – فقط گزارش)
def simplify_vaccine(x):
    if pd.isna(x):
        return 'Unknown'
    x = str(x).lower()
    if 'سینوفارم' in x or 'sinopharm' in x:
        return 'Sinopharm'
    if 'آستراز' in x or 'astraz' in x:
        return 'AstraZeneca'
    if 'برکت' in x:
        return 'Barkat'
    if 'اسپوتنیک' in x:
        return 'Sputnik'
    return 'Other'

df_vax['Vaccine_Type_Simple'] = df_vax['Unnamed: 101'].apply(simplify_vaccine)

# 5) دیتافریم نهایی برای مدل
df_vax_final = df_vax[['Vaccinated', 'Vaccine_Doses']].copy()

# 6) خروجی تحلیلی
print("📐 شکل دیتافریم Vaccination:", df_vax_final.shape)

print("\n🔍 نمونه داده‌ها:")
display(df_vax_final.head(10))

print("\n📊 آمار واکسیناسیون:")
print("درصد واکسینه‌شده‌ها:", round(df_vax_final['Vaccinated'].mean()*100, 2))

print("\n📊 توزیع تعداد دوز:")
display(df_vax_final['Vaccine_Doses'].value_counts().sort_index())

print("\n📊 توزیع نوع واکسن (گزارشی):")
display(df_vax['Vaccine_Type_Simple'].value_counts())

📐 شکل دیتافریم Vaccination: (16780, 2)

🔍 نمونه داده‌ها:

   Vaccinated  Vaccine_Doses
0           0            0.0
1           0            0.0
2           0            0.0
3           0            0.0
4           1            2.0
5           0            0.0
6           0            0.0
7           0            0.0
8           0            0.0
9           0            0.0

📊 آمار واکسیناسیون:
درصد واکسینه‌شده‌ها: 3.43

📊 توزیع تعداد دوز:

Vaccine_Doses
0.0    16205
1.0      107
2.0      354
3.0      106
4.0        8
Name: count, dtype: int64

📊 توزیع نوع واکسن (گزارشی):

Vaccine_Type_Simple
Unknown        16285
Sinopharm        398
Other             45
Barkat            35
AstraZeneca       12
Sputnik            5
Name: count, dtype: int64

«به‌جای اتکا به فیلد بله/خیر، واکسیناسیون را بر اساس تعداد دوز ثبت‌شده بازتعریف کردیم تا خطای داده‌های ناقص حذف شود و اثر ایمنی به‌صورت کمی وارد مدل شود.»

«ستون‌های با فقدان داده بالا (بیش از ۹۰٪)، اطلاعات غیرساخت‌یافته، یا متغیرهایی با احتمال نشت اطلاعات (Data Leakage) حذف شدند تا پایداری و تفسیرپذیری مدل حفظ شود.»

In [ ]:
# =========================
# Drop Irrelevant / High-Missing Columns
# =========================

df = df_raw.copy()

# 1) حذف ستون‌های فامیلی و مشاوره (بر اساس نام)
drop_keywords = [
    'فامیلی',
    'خانوادگی',
    'مشاوره',
    'consult',
    'family'
]

cols_to_drop = [
    col for col in df.columns
    if any(key in str(col) for key in drop_keywords)
]

# 2) حذف ستون‌های Unnamed با missing بالا
missing_threshold = 0.9  # 90 درصد

high_missing_cols = [
    col for col in df.columns
    if col.startswith('Unnamed')
    and df[col].isna().mean() > missing_threshold
]

# 3) حذف نهایی
final_drop_cols = list(set(cols_to_drop + high_missing_cols))

df_cleaned = df.drop(columns=final_drop_cols)

# 4) گزارش
print(f"🧹 تعداد ستون‌های حذف‌شده: {len(final_drop_cols)}")
print("\n🗑 نمونه ستون‌های حذف‌شده:")
for c in final_drop_cols[:20]:
    print("-", c)

print("\n📐 شکل دیتافریم بعد از پاکسازی:")
print(df_cleaned.shape)

🧹 تعداد ستون‌های حذف‌شده: 115

🗑 نمونه ستون‌های حذف‌شده:
- Unnamed: 147
- Unnamed: 126
- Unnamed: 44
- Unnamed: 60
- Unnamed: 134
- Unnamed: 52
- Unnamed: 130
- Unnamed: 48
- Unnamed: 88
- Unnamed: 21
- Unnamed: 113
- Unnamed: 25
- Unnamed: 110
- Unnamed: 135
- Unnamed: 156
- Unnamed: 109
- Unnamed: 41
- Unnamed: 11
- Unnamed: 57
- Unnamed: 15

📐 شکل دیتافریم بعد از پاکسازی:
(16783, 48)